# Generated by Django 4.0.6 on 2023-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Question', max_length=200)),
                ('answer', models.CharField(default='Answer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Headline', max_length=100)),
                ('body_text', models.TextField(default='...', max_length=10000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('description', models.TextField(default='Description', max_length=500)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
            ],
        ),
    ]
