# Generated by Django 4.2.5 on 2023-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.CharField(default='Answer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_sv',
            field=models.CharField(default='Answer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(default='Question', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_sv',
            field=models.CharField(default='Question', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_text_en',
            field=models.TextField(default='...', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_text_sv',
            field=models.TextField(default='...', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='headline_en',
            field=models.CharField(default='Headline', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='headline_sv',
            field=models.CharField(default='Headline', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='description_en',
            field=models.TextField(default='Description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='description_sv',
            field=models.TextField(default='Description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='title_en',
            field=models.CharField(default='Title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='title_sv',
            field=models.CharField(default='Title', max_length=100, null=True),
        ),
    ]
