# Generated by Django 4.2.5 on 2023-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq_answer_en_faq_answer_sv_faq_question_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(default='Description', max_length=2000),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description_en',
            field=models.TextField(default='Description', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description_sv',
            field=models.TextField(default='Description', max_length=2000, null=True),
        ),
    ]
